proxy_app: tcp://127.0.0.1:26658
moniker: app
fast_sync: true
db_backend: goleveldb
db_dir: data
log_level: info
log_format: plain
genesis_file: config/genesis.json
priv_validator_key_file: config/priv_validator_key.json
priv_validator_state_file: data/priv_validator_state.json
priv_validator_laddr: ""
node_key_file: config/node_key.json
abci: socket
filter_peers: false
rpc:
  laddr: tcp://127.0.0.1:26657
  cors_allowed_origins: []
  cors_allowed_methods:
    - HEAD
    - GET
    - POST
  cors_allowed_headers:
    - Origin
    - Accept
    - Content-Type
    - X-Requested-With
    - X-Server-Time
  grpc_laddr: ""
  grpc_max_open_connections: 900
  unsafe: false
  max_open_connections: 900
  max_subscription_clients: 100
  max_subscriptions_per_client: 5
  experimental_subscription_buffer_size: 200
  experimental_websocket_write_buffer_size: 200
  experimental_close_on_slow_client: false
  timeout_broadcast_tx_commit: 50s
  max_body_bytes: 8388608
  max_header_bytes: 1048576
  tls_cert_file: ""
  tls_key_file: ""
  pprof_laddr: localhost:6060
p2p:
  laddr: tcp://0.0.0.0:26656
  external_address: ""
  seeds: ""
  persistent_peers: ""
  upnp: false
  addr_book_file: config/addrbook.json
  addr_book_strict: true
  max_num_inbound_peers: 40
  max_num_outbound_peers: 10
  unconditional_peer_ids: ""
  persistent_peers_max_dial_period: 0s
  flush_throttle_timeout: 100ms
  max_packet_msg_payload_size: 1024
  send_rate: 10485760
  recv_rate: 10485760
  pex: true
  seed_mode: false
  private_peer_ids: ""
  allow_duplicate_ip: false
  handshake_timeout: 20s
  dial_timeout: 3s
mempool:
  version: v2
  recheck: true
  broadcast: true
  wal_dir: ""
  size: 5000
  max_txs_bytes: 83886080
  cache_size: 10000
  keep_invalid_txs_in_cache: false
  max_tx_bytes: 2097152
  max_batch_bytes: 0
  ttl_duration: 1m15s
  ttl_num_blocks: 12
  max_gossip_delay: 0s
  experimental_max_gossip_connections_to_persistent_peers: 0
  experimental_max_gossip_connections_to_non_persistent_peers: 0
statesync:
  enable: false
  rpc_servers: ""
  trust_height: 0
  trust_hash: ""
  trust_period: 168h0m0s
  discovery_time: 15s
  temp_dir: ""
  chunk_request_timeout: 10s
  chunk_fetchers: "4"
fastsync:
  version: v0
consensus:
  only_internal_wal: "true"
  wal_file: data/cs.wal/wal
  timeout_propose: 3.5s
  timeout_propose_delta: 500ms
  timeout_prevote: 1s
  timeout_prevote_delta: 500ms
  timeout_precommit: 1s
  timeout_precommit_delta: 500ms
  timeout_commit: 4.2s
  double_sign_check_height: 0
  skip_timeout_commit: false
  create_empty_blocks: true
  create_empty_blocks_interval: 0s
  peer_gossip_sleep_duration: 100ms
  peer_query_maj23_sleep_duration: 2s
storage:
  discard_abci_responses: true
tx_index:
  indexer: "null"
  psql_conn: ""
instrumentation:
  prometheus: false
  prometheus_listen_addr: :26660
  max_open_connections: 3
  namespace: cometbft
  trace_push_config: ""
  trace_pull_address: ""
  trace_type: noop
  trace_push_batch_size: 1000
  tracing_tables: mempool_tx,mempool_peer_state,consensus_round_state,consensus_block_parts,consensus_block,consensus_vote,consensus_state,consensus_proposal,peers,pending_bytes,received_bytes,abci
  pyroscope_url: ""
  pyroscope_trace: false
  pyroscope_profile_types:
    - cpu
    - alloc_objects
    - inuse_objects
    - goroutines
    - mutex_count
    - mutex_duration
    - block_count
    - block_duration
