Node:
  StartupTimeout: 20s
  ShutdownTimeout: 20s
Core:
  IP: ""
  Port: "9090"
  TLSEnabled: false
  XTokenPath: ""
  AdditionalCoreEndpoints: []
State:
  DefaultKeyName: my_celes_key
  DefaultBackendName: test
  EstimatorAddress: ""
  EnableEstimatorTLS: false
P2P:
  ListenAddresses:
    - /ip4/0.0.0.0/udp/2121/quic-v1/webtransport
    - /ip6/::/udp/2121/quic-v1/webtransport
    - /ip4/0.0.0.0/udp/2121/quic-v1
    - /ip6/::/udp/2121/quic-v1
    - /ip4/0.0.0.0/udp/2121/webrtc-direct
    - /ip6/::/udp/2121/webrtc-direct
    - /ip4/0.0.0.0/tcp/2121
    - /ip6/::/tcp/2121
  AnnounceAddresses: []
  NoAnnounceAddresses:
    - /ip4/127.0.0.1/udp/2121/quic-v1/webtransport
    - /ip4/0.0.0.0/udp/2121/quic-v1/webtransport
    - /ip6/::/udp/2121/quic-v1/webtransport
    - /ip4/0.0.0.0/udp/2121/quic-v1
    - /ip4/127.0.0.1/udp/2121/quic-v1
    - /ip6/::/udp/2121/quic-v1
    - /ip4/0.0.0.0/udp/2121/webrtc-direct
    - /ip4/127.0.0.1/udp/2121/webrtc-direct
    - /ip6/::/udp/2121/webrtc-direct
    - /ip4/0.0.0.0/tcp/2121
    - /ip4/127.0.0.1/tcp/2121
    - /ip6/::/tcp/2121
  MutualPeers: []
  PeerExchange: false
  ConnManager:
    Low: 50
    High: 100
    GracePeriod: 1m0s
RPC:
  Address: localhost
  Port: "26658"
  SkipAuth: false
  CORS:
    Enabled: false
    AllowedOrigins: []
    AllowedHeaders: []
    AllowedMethods: []
Share:
  BlockStoreCacheSize: 128
  UseShareExchange: true
  UseBitswap: true
  EDSStoreParams:
    RecentBlocksCacheSize: 10
  ShrExEDSParams:
    ServerReadTimeout: 5s
    ServerWriteTimeout: 1m0s
    HandleRequestTimeout: 1m0s
    ConcurrencyLimit: 10
    BufferSize: 32768
  ShrExNDParams:
    ServerReadTimeout: 5s
    ServerWriteTimeout: 1m0s
    HandleRequestTimeout: 1m0s
    ConcurrencyLimit: 10
  PeerManagerParams:
    PoolValidationTimeout: 2m0s
    PeerCooldown: 3s
    GcInterval: 30s
    EnableBlackListing: false
  LightAvailability:
    SampleAmount: 16
  Discovery:
    PeersLimit: 5
    AdvertiseInterval: 1h0m0s
Header:
  TrustedHash: ""
  TrustedPeers: []
  Store:
    StoreCacheSize: 512
    IndexCacheSize: 2048
    WriteBatchSize: 512
  Syncer:
    TrustingPeriod: 336h0m0s
  Server:
    WriteDeadline: 8s
    ReadDeadline: 1m0s
    RequestTimeout: 10s
  Client:
    MaxHeadersPerRangeRequest: 64
    RequestTimeout: 8s
DASer:
  SamplingRange: 100
  ConcurrencyLimit: 16
  BackgroundStoreInterval: 10m0s
  SampleFrom: 1
  SampleTimeout: 2m40s
  Enabled: true
