annotations:
  category: celestia
  licenses: Apache-2.0
apiVersion: v2
appVersion: v3.6.0
dependencies:
- name: common-celestia-app
  version: 0.1.3
  repository: https://celestiaorg.github.io/helm-charts
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Celestia App
home: https://celestia.org
icon: https://celestia.org/static/celestia-logo-29451ae35d3bb72cc4b0f17712d44c3a.svg
keywords:
  - celestia
  - celestia-app
maintainers:
  - name: Celestia Labs
    url: https://github.com/celestiaorg/helm-charts
name: celestia-app
sources:
  - https://github.com/celestiaorg/celestia-app
version: 0.0.9